// <auto-generated />
using System;
using GenericRepo.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GenericRepo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240108193516_4mig")]
    partial class _4mig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GenericRepo.Entities.Concrete.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Credit")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("Lessons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2024, 1, 8, 22, 35, 16, 271, DateTimeKind.Local).AddTicks(2454),
                            Credit = 0,
                            Name = "Mat",
                            SchoolId = 1
                        });
                });

            modelBuilder.Entity("GenericRepo.Entities.Concrete.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Schools");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Alibeyköy",
                            CreationDate = new DateTime(2024, 1, 8, 22, 35, 16, 271, DateTimeKind.Local).AddTicks(2315),
                            Name = "Bilgi"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Fatih",
                            CreationDate = new DateTime(2024, 1, 8, 22, 35, 16, 271, DateTimeKind.Local).AddTicks(2326),
                            Name = "KHAS"
                        });
                });

            modelBuilder.Entity("GenericRepo.Entities.Concrete.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SchoolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassName = "EEEN",
                            CreationDate = new DateTime(2024, 1, 8, 22, 35, 16, 271, DateTimeKind.Local).AddTicks(2439),
                            Name = "Bg",
                            SchoolId = 1
                        },
                        new
                        {
                            Id = 2,
                            ClassName = "EEEN",
                            CreationDate = new DateTime(2024, 1, 8, 22, 35, 16, 271, DateTimeKind.Local).AddTicks(2440),
                            Name = "OÜ",
                            SchoolId = 1
                        },
                        new
                        {
                            Id = 3,
                            ClassName = "CMPE",
                            CreationDate = new DateTime(2024, 1, 8, 22, 35, 16, 271, DateTimeKind.Local).AddTicks(2441),
                            Name = "AÖY",
                            SchoolId = 2
                        },
                        new
                        {
                            Id = 4,
                            ClassName = "CMPE",
                            CreationDate = new DateTime(2024, 1, 8, 22, 35, 16, 271, DateTimeKind.Local).AddTicks(2442),
                            Name = "TY",
                            SchoolId = 2
                        });
                });

            modelBuilder.Entity("GenericRepo.Entities.Concrete.StudentLesson", b =>
                {
                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.Property<int?>("LessonId")
                        .HasColumnType("int");

                    b.HasKey("StudentId", "LessonId");

                    b.HasIndex("LessonId");

                    b.ToTable("StudentLesson");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            LessonId = 1
                        },
                        new
                        {
                            StudentId = 2,
                            LessonId = 1
                        },
                        new
                        {
                            StudentId = 3,
                            LessonId = 1
                        },
                        new
                        {
                            StudentId = 4,
                            LessonId = 1
                        });
                });

            modelBuilder.Entity("GenericRepo.Entities.Concrete.Lesson", b =>
                {
                    b.HasOne("GenericRepo.Entities.Concrete.School", "School")
                        .WithMany("Lessons")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("GenericRepo.Entities.Concrete.Student", b =>
                {
                    b.HasOne("GenericRepo.Entities.Concrete.School", "School")
                        .WithMany("Students")
                        .HasForeignKey("SchoolId");

                    b.Navigation("School");
                });

            modelBuilder.Entity("GenericRepo.Entities.Concrete.StudentLesson", b =>
                {
                    b.HasOne("GenericRepo.Entities.Concrete.Lesson", "Lesson")
                        .WithMany("StudentLessons")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("GenericRepo.Entities.Concrete.Student", "Student")
                        .WithMany("StudentLessons")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("GenericRepo.Entities.Concrete.Lesson", b =>
                {
                    b.Navigation("StudentLessons");
                });

            modelBuilder.Entity("GenericRepo.Entities.Concrete.School", b =>
                {
                    b.Navigation("Lessons");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("GenericRepo.Entities.Concrete.Student", b =>
                {
                    b.Navigation("StudentLessons");
                });
#pragma warning restore 612, 618
        }
    }
}
