// <auto-generated />
using System;
using GenericRepo.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GenericRepo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240107232021_3mig")]
    partial class _3mig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GenericRepo.Entities.Concrete.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Credit")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("Lesson");
                });

            modelBuilder.Entity("GenericRepo.Entities.Concrete.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Schools");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Alibeyköy",
                            CreationDate = new DateTime(2024, 1, 8, 2, 20, 21, 179, DateTimeKind.Local).AddTicks(1625),
                            Name = "Bilgi"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Fatih",
                            CreationDate = new DateTime(2024, 1, 8, 2, 20, 21, 179, DateTimeKind.Local).AddTicks(1638),
                            Name = "KHAS"
                        });
                });

            modelBuilder.Entity("GenericRepo.Entities.Concrete.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SchoolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassName = "EEEN",
                            CreationDate = new DateTime(2024, 1, 8, 2, 20, 21, 179, DateTimeKind.Local).AddTicks(1717),
                            Name = "Bg",
                            SchoolId = 1
                        },
                        new
                        {
                            Id = 2,
                            ClassName = "EEEN",
                            CreationDate = new DateTime(2024, 1, 8, 2, 20, 21, 179, DateTimeKind.Local).AddTicks(1719),
                            Name = "OÜ",
                            SchoolId = 1
                        },
                        new
                        {
                            Id = 3,
                            ClassName = "CMPE",
                            CreationDate = new DateTime(2024, 1, 8, 2, 20, 21, 179, DateTimeKind.Local).AddTicks(1720),
                            Name = "AÖY",
                            SchoolId = 2
                        },
                        new
                        {
                            Id = 4,
                            ClassName = "CMPE",
                            CreationDate = new DateTime(2024, 1, 8, 2, 20, 21, 179, DateTimeKind.Local).AddTicks(1721),
                            Name = "TY",
                            SchoolId = 2
                        });
                });

            modelBuilder.Entity("GenericRepo.Entities.Concrete.StudentLesson", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.HasKey("StudentId", "LessonId");

                    b.HasIndex("LessonId");

                    b.ToTable("StudentLesson");
                });

            modelBuilder.Entity("LessonStudent", b =>
                {
                    b.Property<int>("LessonsId")
                        .HasColumnType("int");

                    b.Property<int>("StudentsId")
                        .HasColumnType("int");

                    b.HasKey("LessonsId", "StudentsId");

                    b.HasIndex("StudentsId");

                    b.ToTable("LessonStudent");
                });

            modelBuilder.Entity("GenericRepo.Entities.Concrete.Lesson", b =>
                {
                    b.HasOne("GenericRepo.Entities.Concrete.School", "School")
                        .WithMany("Lessons")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("GenericRepo.Entities.Concrete.Student", b =>
                {
                    b.HasOne("GenericRepo.Entities.Concrete.School", "School")
                        .WithMany("Students")
                        .HasForeignKey("SchoolId");

                    b.Navigation("School");
                });

            modelBuilder.Entity("GenericRepo.Entities.Concrete.StudentLesson", b =>
                {
                    b.HasOne("GenericRepo.Entities.Concrete.Lesson", "Lesson")
                        .WithMany("StudentLessons")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GenericRepo.Entities.Concrete.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LessonStudent", b =>
                {
                    b.HasOne("GenericRepo.Entities.Concrete.Lesson", null)
                        .WithMany()
                        .HasForeignKey("LessonsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GenericRepo.Entities.Concrete.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenericRepo.Entities.Concrete.Lesson", b =>
                {
                    b.Navigation("StudentLessons");
                });

            modelBuilder.Entity("GenericRepo.Entities.Concrete.School", b =>
                {
                    b.Navigation("Lessons");

                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
