// <auto-generated />
using System;
using GenericRepo.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GenericRepo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240102111103_mig1")]
    partial class mig1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GenericRepo.Entities.Concrete.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Schools");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Alibeyköy",
                            CreationDate = new DateTime(2024, 1, 2, 14, 11, 3, 251, DateTimeKind.Local).AddTicks(7402),
                            Name = "Bilgi"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Fatih",
                            CreationDate = new DateTime(2024, 1, 2, 14, 11, 3, 251, DateTimeKind.Local).AddTicks(7413),
                            Name = "KHAS"
                        });
                });

            modelBuilder.Entity("GenericRepo.Entities.Concrete.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SchoolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassName = "EEEN",
                            CreationDate = new DateTime(2024, 1, 2, 14, 11, 3, 251, DateTimeKind.Local).AddTicks(7520),
                            Name = "Bg",
                            SchoolId = 1
                        },
                        new
                        {
                            Id = 2,
                            ClassName = "EEEN",
                            CreationDate = new DateTime(2024, 1, 2, 14, 11, 3, 251, DateTimeKind.Local).AddTicks(7522),
                            Name = "OÜ",
                            SchoolId = 1
                        },
                        new
                        {
                            Id = 3,
                            ClassName = "CMPE",
                            CreationDate = new DateTime(2024, 1, 2, 14, 11, 3, 251, DateTimeKind.Local).AddTicks(7522),
                            Name = "AÖY",
                            SchoolId = 2
                        },
                        new
                        {
                            Id = 4,
                            ClassName = "CMPE",
                            CreationDate = new DateTime(2024, 1, 2, 14, 11, 3, 251, DateTimeKind.Local).AddTicks(7523),
                            Name = "TY",
                            SchoolId = 2
                        });
                });

            modelBuilder.Entity("GenericRepo.Entities.Concrete.Student", b =>
                {
                    b.HasOne("GenericRepo.Entities.Concrete.School", "School")
                        .WithMany("Students")
                        .HasForeignKey("SchoolId");

                    b.Navigation("School");
                });

            modelBuilder.Entity("GenericRepo.Entities.Concrete.School", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
